services:
  sports-booker-auth:
    image: sports-booker-auth:latest
    container_name: sports-booker-auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5073:80"
    networks:
      - dev-net
    env_file:
      - .env

networks:
  dev-net:
    external: true
    