<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

        <AssemblyName>CourtBooker.Auth.Shared</AssemblyName>
        <OutputPath>..\..\Output\</OutputPath>
        <RestorePackagesPath>..\..\Dependencies\Packages\</RestorePackagesPath>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MediatR"/>

        <ProjectReference Include="..\Domain\Domain.csproj"/>
    </ItemGroup>
</Project>
