<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

        <AssemblyName>CourtBooker.Auth.Shared</AssemblyName>
        <OutputPath>..\..\Output\</OutputPath>
        <RestorePackagesPath>..\Dependencies\Packages\</RestorePackagesPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR"/>
        
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>
</Project>
