<Project>
    <ItemGroup>
        <PackageVersion Include="MediatR" Version="12.4.1"/>
        <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.2"/>
        <PackageVersion Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0"/>
        <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.1"/>
        <PackageVersion Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0"/>
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.1"/>
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1"/>
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.1"/>
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1"/>
        <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3"/>
        <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0"/>
        <PackageVersion Include="Elastic.Serilog.Sinks" Version="8.12.3"/>
        <PackageVersion Include="FluentValidation" Version="12.0.0-preview1"/>
        <PackageVersion Include="FluentValidation.AspNetCore" Version="11.3.0"/>
    </ItemGroup>
</Project>