<Project>
    <ItemGroup>
        <PackageVersion Include="MediatR" Version="12.4.1"/>

        <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.2"/>

        <PackageVersion Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0"/>
        <PackageVersion Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0"/>

        <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.1"/>
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.1"/>
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1"/>
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.1"/>
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1"/>
        <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3"/>

        <PackageVersion Include="FluentValidation" Version="12.0.0-preview1"/>
        <PackageVersion Include="FluentValidation.AspNetCore" Version="11.3.0"/>

        <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0"/>
        <PackageVersion Include="Elastic.Serilog.Sinks" Version="8.12.3"/>
        <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.1-dev-00953" />
        <PackageVersion Include="Serilog.Enrichers.Environment" Version="3.0.1"/>

        <PackageVersion Include="Elastic.Extensions.Logging" Version="8.12.3" />
        <PackageVersion Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
        <PackageVersion Include="Azure.Security.KeyVault.Secrets" Version="4.8.0" />
        <PackageVersion Include="Azure.Identity" Version="1.14.0" />
    </ItemGroup>
</Project>