name: courtbooker Auth - Build Docker Image

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  CONTAINER_NAME: courtbooker-auth
  REGISTRY: ghcr.io
  USERNAME: gooozmen
  IMAGE_VERSION: 1.0.${{ github.run_number }}
  RESOURCE_GROUP: CourtBooker-App-Dev

jobs:
  build-test-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Clean artifacts
        run: |
          rm -rf Artifacts/TestResults
          mkdir -p Artifacts/TestResults

      ########################
      # 0 Restore dependencies
      ########################
      - name: Restore dependencies
        run: dotnet restore ./src/CourtBooker-Auth.sln

      ########################
      # 1 Build
      ########################
      - name: Build solution
        run: dotnet build ./src/CourtBooker-Auth.sln --configuration Release --no-restore

      ########################
      # 2️ Test
      ########################
      - name: Run unit tests
        run: |
          dotnet test ./src/CourtBooker-Auth.sln \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=TestResults.trx" \
            --results-directory Artifacts/TestResults

      ########################
      # 3 Report Test Results
      ########################
      - name: Report Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: Artifacts/TestResults/TestResults.trx
          reporter: dotnet-trx