name: CICD - Staging

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]
  workflow_dispatch:

env:
  CONTAINER_NAME: courtbooker-auth
  REGISTRY: ghcr.io
  USERNAME: gooozmen
  IMAGE_VERSION: 1.0.${{ github.run_number }}
  RESOURCE_GROUP: CourtBooker-App-Dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Clean artifacts
        run: |
          rm -rf Artifacts/TestResults
          mkdir -p Artifacts/TestResults

      ########################
      # 0 Restore dependencies
      ########################
      - name: Restore dependencies
        run: dotnet restore ./src/CourtBooker-Auth.sln

      ########################
      # 1 Build
      ########################
      - name: Build solution
        run: dotnet build ./src/CourtBooker-Auth.sln --configuration Release --no-restore

      ########################
      # 2️ Test
      ########################
      - name: Run unit tests
        run: |
          dotnet test ./src/CourtBooker-Auth.sln \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=TestResults.trx" \
            --results-directory Artifacts/TestResults

      ########################
      # 3️ Build Docker Image
      ########################
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.NUGET_PASSWORD }}

      - name: Build, tag and push Docker image
        run: |
          IMAGE_BASE=${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.CONTAINER_NAME }}
          IMAGE_LATEST=$IMAGE_BASE:latest
          IMAGE_VERSIONED=$IMAGE_BASE:${{ env.IMAGE_VERSION }}

          docker build -t $IMAGE_LATEST .
          docker tag $IMAGE_LATEST $IMAGE_VERSIONED

          docker push $IMAGE_LATEST
          docker push $IMAGE_VERSIONED

          echo "Docker image pushed: $IMAGE_VERSIONED"
