# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name:  CI - Build and Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:

    permissions:  # Add permissions for test reporting
      contents: read
      actions: read
      checks: write

    runs-on: Windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ./Build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup
      run: ./setup.ps1
      #load environment variables from secrets
      env:
          NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}
          NUGET_PASSWORD: ${{ secrets.NUGET_PASSWORD }}
      
    - name: build dotnet solution
      run: ./build-solution.ps1

    # Step 4: Run Unit Tests
    - name: run unit tests
      working-directory: ./Build
      run: ./run-tests.ps1

    # Step 6: Parse and Display the Test Results
    - name: Report Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: Artifacts/TestResults.trx
        reporter: dotnet-trx