name:  CICD - Staging

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    #load environment variables from secrets for the whole pipeline
    env:
      CONTAINER_NAME: courtbooker-auth
      REGISTRY: ghcr.io
      USERNAME: gooozmen
      IMAGE_VERSION: 1.0.${{ github.run_number }}
      RESOURCE_GROUP: CourtBooker-App-Dev

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository 
        uses: actions/checkout@v4

      # Step 2: Set Up Dotnet SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # Step 3: Clean Artifacts
      - name: Clean previous artifacts
        run: |
          rm -rf Artifacts/TestResults
          mkdir -p Artifacts/TestResults

      # Step 4: Restore Dependencies
      - name: Restore dependencies
        run: dotnet restore ./src/CourtBooker-Auth.sln

      # Step 5: Build Solution
      - name: Build solution
        run: dotnet build ./src/CourtBooker-Auth.sln --configuration Release --no-restore

      # Step 6: Test Solution
      - name: Run unit tests
        run: |
          dotnet test ./src/CourtBooker-Auth.sln \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=TestResults.trx" \
            --results-directory Artifacts/TestResults

      # Step 6: Test Solution
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.NUGET_PASSWORD }}

      # Step 7: Build, Tag and Push Docker Image
      - name: Build, tag and push Docker image
        run: |
          IMAGE_BASE=${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.CONTAINER_NAME }}
          IMAGE_LATEST=$IMAGE_BASE:latest
          IMAGE_VERSIONED=$IMAGE_BASE:${{ env.IMAGE_VERSION }}

          echo "Building $IMAGE_LATEST"
          docker build -t $IMAGE_LATEST .

          echo "Tagging image as $IMAGE_VERSIONED"
          docker tag $IMAGE_LATEST $IMAGE_VERSIONED

          echo "Pushing both tags..."
          docker push $IMAGE_LATEST
          docker push $IMAGE_VERSIONED

          echo "Docker image pushed: $IMAGE_VERSIONED"

      # Step 8: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 9: Deploy to Azure Container App
      - name: Deploy to Azure Container App
        run: |
          IMAGE_BASE=${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.CONTAINER_NAME }}
          IMAGE_LATEST=$IMAGE_BASE:latest
          az containerapp update \
            --name ${{ env.CONTAINER_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image $IMAGE_LATEST \
            --set-env-vars \
              JWT_KEY=${{ secrets.JWT_KEY }} \
              JWT_ISSUER=${{ secrets.CONTAINER_URL }} \
              JWT_AUDIENCE=${{ secrets.CONTAINER_URL }} \
              AUTH_DB="${{ secrets.AUTH_DB }}" \
              ELASTIC_NODE_URL="${{ secrets.ELASTIC_URL }}" \
              ELASTIC_API_KEY="${{ secrets.ELASTIC_API_KEY }}" \
              ELASTIC_USERNAME="${{ secrets.ELASTIC_USERNAME }}" \
              ELASTIC_PASSWORD="${{ secrets.ELASTIC_PASSWORD }}" \
              ASPNETCORE_ENVIRONMENT="Staging" \