name:  CI - Build and Test

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: Windows-latest

    permissions:  # Add permissions for test reporting
      contents: read
      actions: read
      checks: write
    
    defaults:
      run:
        shell: pwsh
        working-directory: ./Build

    #load environment variables from secrets for the whole pipeline
    env:
      NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}
      NUGET_PASSWORD: ${{ secrets.NUGET_PASSWORD }}
      DOCKER_IMAGE_VERSION: ${{ github.run_number }}
      # AUTH_DB: ${{ secrets.AUTH_DB }}
      # JWT_KEY: ${{ secrets.JWT_KEY}}
      # JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
      # JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
      # ELASTIC_NODE_URL: ${{ secrets.ELASTIC_NODE_URL }}
      # ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
      # ELASTIC_USERNAME: ${{ secrets.ELASTIC_USERNAME }}
      # ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}

    steps:
    # Step 1: Checkout the Repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Step 3: Install Dependencies
    - name: Setup
      run: ./setup.ps1
      
    # Step 4: Build the Solution
    - name: build dotnet solution
      run: ./build-solution.ps1

    # Step 5: Run Unit Tests
    - name: run unit tests
      run: ./run-tests.ps1

    # # Step 6: Parse and Display the Test Results
    # - name: Report Test Results
    #   uses: dorny/test-reporter@v1
    #   if: always()
    #   with:
    #     name: Test Results
    #     path: Artifacts/TestResults.trx
    #     reporter: dotnet-trx

    # step 7: Build Docker Image
    - name: Build Image
      run: ./build-image.ps1